name: Task
description: The smallest form of work to be completed.
projects: ["Bronstrom/Spotilight"]
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this task!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Basic details about your request for the application. 
      placeholder: Enter a description
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What requirements are needed to be completed in order for this issue to be
        fulfilled.
      placeholder: Enter requirements
      value: |
            - [ ]
            - [ ]
            - [ ]
  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation details
      description: Any additional details that may be helpful to completing this issue?
      placeholder: Enter implementation details
