name: Epic
description: Large body of work containing user stories.
projects: ["Bronstrom/Spotilight"]
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this epic!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What user stories does this entail? What is the scope of this epic?
      placeholder: Enter a description
  - type: textarea
    id: stories
    attributes:
      label: Stories
      description: List any stories that should be associated with this epic.
      value: |
            - [ ]
            - [ ]
            - [ ]
