name: Epic
description: Large body of work containing user stories.
title: ""
projects: ["Bronstrom/Spotilight"]
body:
  - type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this epic!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What user stories does this entail? What is the scope of this epic?
      placeholder: Enter a description
    validations:
      required: true
  - type: textarea
    id: stories
    attributes:
      label: Stories
      description: List any stories that should be associated with this epic.
      value: "- [ ]
              - [ ]
              - [ ]"
    validations:
      required: false
