name: Task
description: The smallest form of work to be completed.
title: ""
label: ["feature"]
projects: ["Bronstrom/Spotilight"]
body:
  - type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this task!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Basic details about your request for the application. 
      placeholder: Enter a description
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What requirements are needed to be completed in order for this issue to be
        fulfilled.
      placeholder: Enter requirements
      value: "- [ ]\n
              - [ ]\n
              - [ ]"
    validations:
      required: true
  - type: textarea
    id: implementation-details
    attributes:
      label: Any additional implementation details?
      description: Any additional details that may be helpful to completing this issue?
      placeholder: Enter implementation details
    validations:
      required: false
